# This file was generated by GoReleaser. DO NOT EDIT.
cask "dsmctl" do
  version "0.1.1"

  on_macos do
    sha256 "47fabaf5cd5ce67b02c43f215c64797744a0be11fcb0753c130b494f05653e6d"
    url "https://github.com/laurenschristian/dsmctl/releases/download/v#{version}/dsmctl_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "a79e84f80ec37b5a2eba42f1c89660ebe3a57e95744c9ce741f35c6450399ebc"
      url "https://github.com/laurenschristian/dsmctl/releases/download/v#{version}/dsmctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "448e995109c4707bc034bc80a51562998f305faf110cdd848169057bcc709355"
      url "https://github.com/laurenschristian/dsmctl/releases/download/v#{version}/dsmctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dsmctl"
  desc "CLI and MCP server for Synology DSM"
  homepage "https://github.com/laurenschristian/dsmctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dsmctl"
  manpage "man/dsmctl.1"
  bash_completion "completions/dsmctl.bash"
  fish_completion "completions/dsmctl.fish"
  zsh_completion "completions/_dsmctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dsmctl"]
    end
  end

  # No zap stanza required
end
