# This file was generated by GoReleaser. DO NOT EDIT.
cask "dsmctl" do
  version "0.1.2"

  on_macos do
    sha256 "67a17c52cfbfe5ba97bb0d66a745616a23f67e89997769dbd3b12d1a50c29bfd"
    url "https://github.com/laurenschristian/dsmctl/releases/download/v#{version}/dsmctl_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "7ef30e258ef7451df00e11ef465fe1634cf7414906dd0eb74ffaf71c3c19a739"
      url "https://github.com/laurenschristian/dsmctl/releases/download/v#{version}/dsmctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dd5de7aeafd1b1d243699c3b31fbe2633bfe6e8bcf3b2169b8ebc6f2ecf34be9"
      url "https://github.com/laurenschristian/dsmctl/releases/download/v#{version}/dsmctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dsmctl"
  desc "CLI and MCP server for Synology DSM"
  homepage "https://github.com/laurenschristian/dsmctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dsmctl"
  manpage "man/dsmctl.1"
  bash_completion "completions/dsmctl.bash"
  fish_completion "completions/dsmctl.fish"
  zsh_completion "completions/_dsmctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dsmctl"]
    end
  end

  # No zap stanza required
end
