# This file was generated by GoReleaser. DO NOT EDIT.
cask "dsmctl" do
  version "0.1.3"

  on_macos do
    sha256 "1111a0d1393d6f4a0b7984e346e3fd16158c526cbec6206c536cebecd115c69e"
    url "https://github.com/laurenschristian/dsmctl/releases/download/v#{version}/dsmctl_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "5fa663d21d87b1e54fbd0414cba6cc85f8d4858b5a618e3cbd0430c960b37545"
      url "https://github.com/laurenschristian/dsmctl/releases/download/v#{version}/dsmctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4787b765f798d0b543513785863cf0290746bceffa4eaa8afaa57f2c8ae1d626"
      url "https://github.com/laurenschristian/dsmctl/releases/download/v#{version}/dsmctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dsmctl"
  desc "CLI and MCP server for Synology DSM"
  homepage "https://github.com/laurenschristian/dsmctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dsmctl"
  manpage "man/dsmctl.1"
  bash_completion "completions/dsmctl.bash"
  fish_completion "completions/dsmctl.fish"
  zsh_completion "completions/_dsmctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dsmctl"]
    end
  end

  # No zap stanza required
end
