# This file was generated by GoReleaser. DO NOT EDIT.
cask "eerox" do
  version "0.2.1"

  on_macos do
    sha256 "22b68cd7f10c812048e186d78817c2d5d34c68f7751c0839341cf814b760afe5"
    url "https://github.com/laurenschristian/eerox/releases/download/v#{version}/eerox_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "1bfb3ff9852a853efac6776ce59148a2f6e2e13de31953a7a162051a84e763e8"
      url "https://github.com/laurenschristian/eerox/releases/download/v#{version}/eerox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1929b50121c2bd1ad9a2b77b4f2d4383fd49545266cc4c17afc8ac941360d882"
      url "https://github.com/laurenschristian/eerox/releases/download/v#{version}/eerox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "eerox"
  desc "CLI and MCP server for eero mesh networks"
  homepage "https://github.com/laurenschristian/eerox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eerox"
  manpage "man/eerox.1"
  bash_completion "completions/eerox.bash"
  fish_completion "completions/eerox.fish"
  zsh_completion "completions/_eerox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eerox"]
    end
  end

  # No zap stanza required
end
