# This file was generated by GoReleaser. DO NOT EDIT.
cask "eerox" do
  version "0.2.0"

  on_macos do
    sha256 "12e43a15f843474e6b572074f831459c6008ba59e13ac3f78102a94bca55332a"
    url "https://github.com/laurenschristian/eerox/releases/download/v#{version}/eerox_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "013f4591c8d1e67bff8c4976fa0d72523e82eff0f0d7cbe68f14c0a16cfec7aa"
      url "https://github.com/laurenschristian/eerox/releases/download/v#{version}/eerox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1a8989868ed801f648cc0feb60fcab7968a7cbd1ecaa644f9550db342f22d16"
      url "https://github.com/laurenschristian/eerox/releases/download/v#{version}/eerox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "eerox"
  desc "CLI and MCP server for eero mesh networks"
  homepage "https://github.com/laurenschristian/eerox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eerox"
  manpage "man/eerox.1"
  bash_completion "completions/eerox.bash"
  fish_completion "completions/eerox.fish"
  zsh_completion "completions/_eerox"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eerox"]
    end
  end

  # No zap stanza required
end
