# This file was generated by GoReleaser. DO NOT EDIT.
cask "finctl" do
  version "0.7.0"

  on_macos do
    sha256 "d41acf97b153dea6a1932b8184b4e50527abc1622645f522224a35df5618df96"
    url "https://github.com/laurenschristian/finctl/releases/download/v#{version}/finctl_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "9ff252cfcd25bf509a4d445729dd66a0978175f3f1c8cfbfafbfe2a92ea15b67"
      url "https://github.com/laurenschristian/finctl/releases/download/v#{version}/finctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa0a4c9d6d5aeb26d2ca077ebe462fa8f619d869b5795ca526ff95cdbb77c3c9"
      url "https://github.com/laurenschristian/finctl/releases/download/v#{version}/finctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "finctl"
  desc "CLI and MCP server for personal finance"
  homepage "https://github.com/laurenschristian/finctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "finctl"
  manpage "man/finctl.1"
  bash_completion "completions/finctl.bash"
  fish_completion "completions/finctl.fish"
  zsh_completion "completions/_finctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/finctl"]
    end
  end

  # No zap stanza required
end
