# This file was generated by GoReleaser. DO NOT EDIT.
cask "finctl" do
  version "0.4.0"

  on_macos do
    sha256 "b8a8cdf8da6df7b37ea85b474507b792544c71349ac182567283b179641f8667"
    url "https://github.com/laurenschristian/finctl/releases/download/v#{version}/finctl_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "3f358e72e42a7137b02132e6501d363dd515cede8dafe49488351fe9a5dc58ca"
      url "https://github.com/laurenschristian/finctl/releases/download/v#{version}/finctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8c6f46f61ac5dcf9cff23e80744dbda5da4b3e5c9ee55bd9477bc33680f0b20b"
      url "https://github.com/laurenschristian/finctl/releases/download/v#{version}/finctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "finctl"
  desc "CLI and MCP server for personal finance"
  homepage "https://github.com/laurenschristian/finctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "finctl"
  manpage "man/finctl.1"
  bash_completion "completions/finctl.bash"
  fish_completion "completions/finctl.fish"
  zsh_completion "completions/_finctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/finctl"]
    end
  end

  # No zap stanza required
end
