# This file was generated by GoReleaser. DO NOT EDIT.
cask "finctl" do
  version "1.0.0"

  on_macos do
    sha256 "ec5ba13bb125036721ffab35823e13f6cc26c50e4f1b6896ee2f2fd4ae70f829"
    url "https://github.com/laurenschristian/finctl/releases/download/v#{version}/finctl_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "bcbb6a2eec881cee920992e9bb9ccddac74f1d8f78dec6a2759558cc483fe81c"
      url "https://github.com/laurenschristian/finctl/releases/download/v#{version}/finctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9e77f1544e072d5344b55737c38f1c6a62d937a91aa264dbeda8f5c724046562"
      url "https://github.com/laurenschristian/finctl/releases/download/v#{version}/finctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "finctl"
  desc "CLI and MCP server for personal finance"
  homepage "https://github.com/laurenschristian/finctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "finctl"
  manpage "man/finctl.1"
  bash_completion "completions/finctl.bash"
  fish_completion "completions/finctl.fish"
  zsh_completion "completions/_finctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/finctl"]
    end
  end

  # No zap stanza required
end
