# This file was generated by GoReleaser. DO NOT EDIT.
cask "ibkrctl" do
  version "0.4.0"

  on_macos do
    sha256 "a69452141b5b22a10fafdd7cedcae74212eed45f564cdb883abc7d2d852bede4"
    url "https://github.com/laurenschristian/ibkrctl/releases/download/v#{version}/ibkrctl_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "a121b488f0b35c376e96504c6eaf5413e2936a638aeecc77967e740c97c3df77"
      url "https://github.com/laurenschristian/ibkrctl/releases/download/v#{version}/ibkrctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5455c263fb9de52637f339474206878cb8bea011e5a31969df46ce781716cee2"
      url "https://github.com/laurenschristian/ibkrctl/releases/download/v#{version}/ibkrctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ibkrctl"
  desc "CLI and MCP server for Interactive Brokers"
  homepage "https://github.com/laurenschristian/ibkrctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ibkrctl"
  manpage "man/ibkrctl.1"
  bash_completion "completions/ibkrctl.bash"
  fish_completion "completions/ibkrctl.fish"
  zsh_completion "completions/_ibkrctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ibkrctl"]
    end
  end

  # No zap stanza required
end
