# This file was generated by GoReleaser. DO NOT EDIT.
cask "ibkrctl" do
  version "0.4.1"

  on_macos do
    sha256 "8a12f98d3b13ab56d738b622ce9a04d183a79b23023dddf3fb2400f66f0d9b6d"
    url "https://github.com/laurenschristian/ibkrctl/releases/download/v#{version}/ibkrctl_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "eceb55a9f3bf129c4403e6a1209199ff503b0e905decd30476d5eceff2ec32e6"
      url "https://github.com/laurenschristian/ibkrctl/releases/download/v#{version}/ibkrctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "36ded27b417958f696089ea731a5f462175380855285e9a6d72df4f55c9a9b39"
      url "https://github.com/laurenschristian/ibkrctl/releases/download/v#{version}/ibkrctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ibkrctl"
  desc "CLI and MCP server for Interactive Brokers"
  homepage "https://github.com/laurenschristian/ibkrctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ibkrctl"
  manpage "man/ibkrctl.1"
  bash_completion "completions/ibkrctl.bash"
  fish_completion "completions/ibkrctl.fish"
  zsh_completion "completions/_ibkrctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ibkrctl"]
    end
  end

  # No zap stanza required
end
