# This file was generated by GoReleaser. DO NOT EDIT.
cask "ibkrctl" do
  version "0.1.0"

  on_macos do
    sha256 "680e6418d1ec9cd0083063c0c44c4bcb6b9a40f0370ddb6fe7f34e2025987d0e"
    url "https://github.com/laurenschristian/ibkrctl/releases/download/v#{version}/ibkrctl_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "0be6cfb2df6149fa175272c69579f6757bab6540d1b7d473817430748cdcd1eb"
      url "https://github.com/laurenschristian/ibkrctl/releases/download/v#{version}/ibkrctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3e98e052bca55796c156d2a3ac86238fabe2c87d6e75a4ed76c0792bc8e206c8"
      url "https://github.com/laurenschristian/ibkrctl/releases/download/v#{version}/ibkrctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ibkrctl"
  desc "CLI and MCP server for Interactive Brokers"
  homepage "https://github.com/laurenschristian/ibkrctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ibkrctl"
  manpage "man/ibkrctl.1"
  bash_completion "completions/ibkrctl.bash"
  fish_completion "completions/ibkrctl.fish"
  zsh_completion "completions/_ibkrctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ibkrctl"]
    end
  end

  # No zap stanza required
end
